name: Ejecutar main.py

on:
  push:
    branches:
      - aprendiendo-github-actions

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run main.py
        run: python main.py