name: Aprendiendo GitHub Actions
run-name: ¡Estoy aprendiendo GitHub Actions!

on: [push]

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run main.py
        run: python hola_mundo.py